version: "3"

services:
  influxdb:
    container_name: influxdb
    image: influxdb:2.3.0
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2:rw
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:8.4.7
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - influxdb

volumes:
  influxdb-data:
  grafana-data:
