{
 "title": "MOT",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "MOT Power",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gain\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"adbox-telescopes\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"B3\" or r[\"_field\"] == \"B2\" or r[\"_field\"] == \"B1\" or r[\"_field\"] == \"A3\" or r[\"_field\"] == \"A2\" or r[\"_field\"] == \"A1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "MOT Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"gain\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"adbox-telescopes\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"B3\" or r[\"_field\"] == \"B2\" or r[\"_field\"] == \"B1\" or r[\"_field\"] == \"A3\" or r[\"_field\"] == \"A2\" or r[\"_field\"] == \"A1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dispenser Current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"gain\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hmp4040\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"i3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Vacuum Pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "from(bucket: \"gain\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"raspiadc\" and\r\n    r._field == \"pressure_sensor\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "X Tilt (MOT Chamber)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  Datum AS \"time\",\n  MOT_Kammer_TiltX\nFROM Messungen\nWHERE\n  $__timeFilter(Datum)\nORDER BY Datum"
    }
   ]
  },
  {
   "title": "Y Tilt (MOT Chamber)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  Datum AS \"time\",\n  MOT_Kammer_TiltY\nFROM Messungen\nWHERE\n  $__timeFilter(Datum)\nORDER BY Datum"
    }
   ]
  },
  {
   "title": "Reference Laser",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gain\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"linien-reference\" and r[\"_field\"] == \"lock\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Cooling Laser",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gain\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"linien-cooling\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lock\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Repumper Laser",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gain\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"linien-repumper\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lock\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Cooling TA",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gain\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"xport1\" and\r\n    r._field == \"tec_2_object_temperature\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  }
 ]
}