version: "3.1"

services:
  mariadb:
    container_name: mariadb
    image: mariadb:12.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"

volumes:
  mariadb-data:
